# Generated by Django 5.2.5 on 2025-09-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decpet', models.CharField(default='', max_length=255, verbose_name='描述decpet')),
                ('job_name', models.CharField(default='', max_length=25, verbose_name='任务名称job_name')),
                ('trigger_name', models.CharField(default='', max_length=25, verbose_name='触发器trigger_name')),
                ('action_type', models.CharField(choices=[('date', 'date'), ('cron', 'cron')], default='cron', max_length=25, verbose_name='调度类型')),
                ('job_state', models.IntegerField(choices=[(0, '停止'), (1, '启动')], default=0, verbose_name='任务状态job_state')),
                ('job_rate', models.CharField(default='', help_text='调度类型 对应 参数（执行频率）  例：<br/>\n                    1、date：2025年9月20日 凌晨一点 执行任务<br/>参数值：2025-9-20 01:00:00 <br/>\n                    2、cron：每天 凌晨两点 执行任务 (秒 分 时 日 月 星期 年)<br/>参数值：0 0 2 * * * *', max_length=50, verbose_name='执行频率job_rate')),
                ('time', models.IntegerField(default=0, verbose_name='执行次数')),
                ('func_name', models.CharField(default='', max_length=255, verbose_name='程序名func_name')),
                ('args_list', models.CharField(default='', help_text='请输入 JSON 格式，例如：{"ip": "127.0.0.1", "param1": "abc"}', max_length=255, verbose_name='参数列表args_list')),
            ],
            options={
                'verbose_name': '定时任务表',
                'verbose_name_plural': '定时任务表',
            },
        ),
    ]
