# Generated by Django 5.2.5 on 2025-11-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_time_limit', models.BooleanField(default=False)),
                ('check_interval', models.IntegerField(default=900)),
                ('email_enabled', models.BooleanField(default=True)),
                ('qq_enabled', models.BooleanField(default=False)),
                ('weixin_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '全局通知配置',
                'verbose_name_plural': '全局通知配置',
            },
        ),
        migrations.CreateModel(
            name='StockMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
            ],
            options={
                'verbose_name': '股票监控配置',
                'verbose_name_plural': '股票监控配置',
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('user', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('sender', models.EmailField(max_length=254)),
                ('title', models.CharField(default='通知标题', max_length=200)),
                ('receivers', models.TextField(help_text='多个邮箱用英文逗号分隔')),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.notificationconfig')),
            ],
            options={
                'verbose_name': 'Email 配置',
                'verbose_name_plural': 'Email 配置',
            },
        ),
        migrations.CreateModel(
            name='QQConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=300)),
                ('qq_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=200)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.notificationconfig')),
            ],
            options={
                'verbose_name': 'QQ 配置',
                'verbose_name_plural': 'QQ 配置',
            },
        ),
        migrations.CreateModel(
            name='WeixinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_id', models.CharField(max_length=100)),
                ('agent_id', models.CharField(max_length=50)),
                ('corp_secret', models.CharField(max_length=200)),
                ('to_user', models.CharField(default='@all', max_length=200)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='config.notificationconfig')),
            ],
            options={
                'verbose_name': '企业微信配置',
                'verbose_name_plural': '企业微信配置',
            },
        ),
    ]
