# Generated by Django 5.2.5 on 2025-11-22 10:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': '告警分类',
                'verbose_name_plural': '告警分类',
            },
        ),
        migrations.CreateModel(
            name='AlertSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#FF0000', max_length=20)),
                ('icon', models.CharField(default='❗', max_length=10)),
            ],
            options={
                'verbose_name': '告警等级',
                'verbose_name_plural': '告警等级',
            },
        ),
        migrations.CreateModel(
            name='AlertContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='告警内容')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alertcontent.alertcategory')),
                ('severity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alertcontent.alertseverity')),
            ],
            options={
                'verbose_name': '告警内容',
                'verbose_name_plural': '告警内容',
            },
        ),
    ]
