"""
Django settings for goamas project.


Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@h(6)a#^*u_$sq-i*^)fzf3hqo61(+h69s%+1!$%^%=t^+9ov)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 测试允许所有访问
ALLOWED_HOSTS = ['*']
# 生产访问控制
# ALLOWED_HOSTS = ["example.com", "api.example.com", "192.168.1.10"]

#版本说明
SYSTEM_NAME = '通用运维自动化'
SOFTWARE_VERSION = 'v1.0.0'

# Application definition

INSTALLED_APPS = [
    'simplepro',
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'joblist',
    'joblist_scheduler',
    #'ckeditor5',  # django-ckeditor5
    #'ckeditor5.fields',
    "django_ckeditor_5",
    'alertcontent',
    'config',

]

CKEDITOR_5_CONFIGS = {
    "default": {
        "language": "zh-cn",
        "toolbar": [
            "heading", "|",
            "bold", "italic", "link", "underline", "strikethrough",
            "|", "bulletedList", "numberedList", "blockQuote",
            "|", "insertTable", "codeBlock", "imageUpload",
            "|", "undo", "redo"
        ],
    }
}

# # CKEditor5 配置（Classic Editor 为例）
# CKEDITOR_5 = {
#     "default": {
#         "editor": "classic",  # classic / balloon / inline / document
#         "language": "zh-cn",
#         "toolbar": [
#             "heading","|","bold","italic","underline","link","bulletedList","numberedList",
#             "blockQuote","undo","redo","code","codeBlock","highlight"
#         ],
#         "height": 300,
#         "placeholder": "请输入告警内容",
#     }
# }

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 注意要放在 Django CommonMiddleware 之前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 加入simplepro的中间件
    'simplepro.middlewares.SimpleMiddleware'
]

ROOT_URLCONF = 'goamas.urls'

# 允许上传的文件目录
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # 确保包含全局模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goamas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

from decouple import config
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # Django 用 mysql 引擎
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# 在Django的配置文件settings.py中，有两个配置参数是跟时间与时区有关的，分别是TIME_ZONE和USE_TZ
#
# 如果USE_TZ设置为True时，Django会使用系统默认设置的时区，即America/Chicago，此时的TIME_ZONE不管有没有设置都不起作用。
# 如果USE_TZ 设置为False，而TIME_ZONE设置为None，则Django还是会使用默认的America/Chicago时间。若TIME_ZONE设置为其它时区的话，
# 则还要分情况，如果是Windows系统，则TIME_ZONE设置是没用的，Django会使用本机的时间。如果为其他系统，则使用该时区的时间，
# 设置USE_TZ = False, TIME_ZONE = 'Asia/Shanghai', 则使用上海的UTC时间。

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'


#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

#USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#-----------------simplepro配置-----------------------------------
SIMPLEPRO_SECRET_KEY = config('SIMPLEPRO_SECRET_KEY')
#-----------------------------------------------以下三个参数是配套的，要一起用
#SIMPLEUI_HOME_PAGE = 'https://www.proginn.com/'
# 标题
#SIMPLEUI_HOME_TITLE = '欢迎使用系统管理后台'
# 图标
#SIMPLEUI_HOME_ICON = 'fa fa-user'
#-----------------------------------------------
# 隐藏监控图表
SIMPLEPRO_MONIT_DISPLAY = True
# 验证码开关
SIMPLEPRO_CAPTCHA_ENABLED = False

###############################################################
# STATIC_URL = '/static/'
#
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')   # 用于 collectstatic 收集的目录
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),  # 如果你有额外的静态目录
# ]



###############################################################
# 项目根目录
BASE_DIR = Path(__file__).resolve().parent.parent

# URL 前缀
STATIC_URL = '/static/'

# collectstatic 收集的目标目录
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 额外的静态文件目录
STATICFILES_DIRS = [
    BASE_DIR / 'static',        # 项目自带静态文件
    # 如果有其他静态目录，可以继续加，比如：
    # BASE_DIR / 'assets',
    # Path('/var/www/external_static'),
]
###############################################################


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

#确定库是否会在数据导入中使用数据库事务，以确保安全
IMPORT_EXPORT_USE_TRANSACTIONS = True

REDIS_SERVER_URL = config('REDIS_SERVER_URL') #DB设为1
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config('REDIS_LOCATION'),  # 带用户名密码 + DB=1
        "TIMEOUT": None,  # 永久缓存
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

